In [9]:
import pandas as pd 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np

In [10]:
from sklearn.datasets import load_iris
iris= load_iris()

In [11]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [1]:
from sklearn.model_selection import cross_val_score

In [21]:
score_lg= cross_val_score(LogisticRegression(max_iter=2000), iris.data, iris.target)
score_lg

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [27]:
np.average(score_lg)

np.float64(0.9733333333333334)

In [22]:
score_svm= cross_val_score(SVC(), iris.data, iris.target)
score_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [26]:
np.average(score_svm)

np.float64(0.9666666666666666)

In [23]:
score_rf= cross_val_score(RandomForestClassifier(), iris.data, iris.target)
score_rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [25]:
np.average(score_rf)

np.float64(0.9666666666666668)